package fronius

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

type FroniusCollector struct {
	baseURL              string
	httpClient           *http.Client
	energyDayDesc        *prometheus.Desc
	energyYearDesc       *prometheus.Desc
	energyTotalDesc      *prometheus.Desc
	powerGridDesc        *prometheus.Desc
	powerLoadDesc        *prometheus.Desc
	powerPVDesc          *prometheus.Desc
	autonomyDesc         *prometheus.Desc
	selfConsumptionDesc  *prometheus.Desc
	upDesc               *prometheus.Desc
}

func NewFroniusCollector(baseURL string) *FroniusCollector {
	return &FroniusCollector{
		baseURL: baseURL,
		httpClient: &http.Client{
			Timeout: 10 * time.Second,
		},
		energyDayDesc: prometheus.NewDesc(
			"fronius_energy_day_watts",
			"Energy produced today in Watts",
			nil, nil,
		),
		energyYearDesc: prometheus.NewDesc(
			"fronius_energy_year_watts",
			"Energy produced year to date in Watts",
			nil, nil,
		),
		energyTotalDesc: prometheus.NewDesc(
			"fronius_energy_total_watts",
			"Energy produced by the system to date in Watts",
			nil, nil,
		),
		powerGridDesc: prometheus.NewDesc(
			"fronius_power_grid_watts",
			"Power to or from the grid in Watts",
			nil, nil,
		),
		powerLoadDesc: prometheus.NewDesc(
			"fronius_power_load_watts",
			"Power consumed by the load in Watts",
			nil, nil,
		),
		powerPVDesc: prometheus.NewDesc(
			"fronius_power_pv_watts",
			"Power generated by the photovoltaic cells in Watts",
			nil, nil,
		),
		autonomyDesc: prometheus.NewDesc(
			"fronius_autonomy_ratio",
			"Relative autonomy ratio of the system",
			nil, nil,
		),
		selfConsumptionDesc: prometheus.NewDesc(
			"fronius_self_consumption_ratio",
			"Self consumption ratio of the system",
			nil, nil,
		),
		upDesc: prometheus.NewDesc(
			"fronius_up",
			"Whether the Fronius inverter is reachable (1 = up, 0 = down)",
			nil, nil,
		),
	}
}

func (c *FroniusCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- c.energyDayDesc
	ch <- c.energyYearDesc
	ch <- c.energyTotalDesc
	ch <- c.powerGridDesc
	ch <- c.powerLoadDesc
	ch <- c.powerPVDesc
	ch <- c.autonomyDesc
	ch <- c.selfConsumptionDesc
	ch <- c.upDesc
}

func (c *FroniusCollector) Collect(ch chan<- prometheus.Metric) {
	data, err := c.fetchData()
	if err != nil {
		log.Printf("fronius: failed to fetch data: %v", err)
		ch <- prometheus.MustNewConstMetric(c.upDesc, prometheus.GaugeValue, 0)
		return
	}

	ch <- prometheus.MustNewConstMetric(c.upDesc, prometheus.GaugeValue, 1)
	ch <- prometheus.MustNewConstMetric(c.energyDayDesc, prometheus.GaugeValue, data.Body.Data.Site.EDay)
	ch <- prometheus.MustNewConstMetric(c.energyYearDesc, prometheus.GaugeValue, data.Body.Data.Site.EYear)
	ch <- prometheus.MustNewConstMetric(c.energyTotalDesc, prometheus.GaugeValue, data.Body.Data.Site.ETotal)
	ch <- prometheus.MustNewConstMetric(c.powerGridDesc, prometheus.GaugeValue, data.Body.Data.Site.PGrid)
	ch <- prometheus.MustNewConstMetric(c.powerLoadDesc, prometheus.GaugeValue, data.Body.Data.Site.PLoad)
	ch <- prometheus.MustNewConstMetric(c.powerPVDesc, prometheus.GaugeValue, data.Body.Data.Site.PPV)
	ch <- prometheus.MustNewConstMetric(c.autonomyDesc, prometheus.GaugeValue, data.Body.Data.Site.RelAutonomy)
	ch <- prometheus.MustNewConstMetric(c.selfConsumptionDesc, prometheus.GaugeValue, data.Body.Data.Site.RelSelfConsumption)
}

func (c *FroniusCollector) fetchData() (FroniusResponse, error) {
	url := fmt.Sprintf("%s/solar_api/v1/GetPowerFlowRealtimeData.fcgi?Scope=System&query=CommonInverterData", c.baseURL)
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return FroniusResponse{}, err
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return FroniusResponse{}, err
	}
	defer resp.Body.Close()

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		return FroniusResponse{}, err
	}

	var fr FroniusResponse
	err = json.Unmarshal(b, &fr)
	if err != nil {
		return FroniusResponse{}, err
	}

	return fr, nil
}